name: Check for Release

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Release
        uses: octokit/rest.js@v2
        with:
          github-token: ${{ secrets.EXTERNAL_REPO_PAT }}
          method: GET
          url: https://api.github.com/repos/other-person/other-repo/releases/latest

      - name: Print Release Info
        run: |
          echo "Release Name: ${{ steps.check-release.outputs.data.name }}"
          echo "Release Tag: ${{ steps.check-release.outputs.data.tag_name }}"
        if: steps.check-release.outputs.status == 200
