name: Check for Release

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Check for Release
        id: get-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: Snowflake-Labs
          repo: terraform-provider-snowflake
          excludes: prerelease, draft
        
      - name: Get Your Repository's Version
        id: get-version
        run: |
          version=$(cat src/snowflake_resources/snowflake_provider.ts | grep -oE 'providerVersionConstraint: "[0-9]+\.[0-9]+\.[0-9]+"' | awk -F'"' '{print $2}')
          echo "::set-output name=MY_VERSION::$version"
          echo $version
        shell: bash

      - name: Compare Release and Version
        id: compare-release-version
        run: |
          release="${{ steps.get-release.outputs.release }}"
          extracted_version="${{ steps.get-version.outputs.MY_VERSION }}"

          if [ "$release" = "$extracted_version" ]; then
            echo "Versions Match: true"
            echo "::set-output name=MATCHES::true"
          else
            echo "Versions Do Not Match: false"
            echo "::set-output name=MATCHES::false"
          fi
        shell: bash
