name: Check for Release

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Check for Release
        uses: octokit/rest.js@latest
        with:
          github-token: ${{ secrets.EXTERNAL_REPO_PAT }}
          method: GET
          url: https://api.github.com/repos/other-person/other-repo/releases/latest

      - name: Print Release Info
        run: |
          echo "Release Name: ${{ steps.check-release.outputs.data.name }}"
          echo "Release Tag: ${{ steps.check-release.outputs.data.tag_name }}"
        if: steps.check-release.outputs.status == 200
