/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";

    export interface Alert_Alert_Schedule {
        readonly cron?: {readonly expression: string; readonly time_zone: string; };
        readonly interval?: number;
    }

export interface AlertConfig extends TerraformMetaArguments {
    action: string;
    condition: string;
    database: string;
    name: string;
    schema: string;
    warehouse: string;
    alert_schedule?: Alert_Alert_Schedule[];
    comment?: string;
    enabled?: boolean;
}

export class Alert extends TerraformResource {
    _action: string;
    _condition: string;
    _database: string;
    _name: string;
    _schema: string;
    _warehouse: string;
    _alert_schedule?: Alert_Alert_Schedule[];
    _comment?: string;
    _enabled?: boolean;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: AlertConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_alert",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._action = config.action;
        
        this._condition = config.condition;
        
        this._database = config.database;
        
        this._name = config.name;
        
        this._schema = config.schema;
        
        this._warehouse = config.warehouse;
        
        this._alert_schedule = config.alert_schedule;
        
        this._comment = config.comment;
        
        this._enabled = config.enabled;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            action: this._action,
            condition: this._condition,
            database: this._database,
            name: this._name,
            schema: this._schema,
            warehouse: this._warehouse,
            alert_schedule: this._alert_schedule,
            comment: this._comment,
            enabled: this._enabled,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_alert.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get action(): string {
        return this._action
    }

    public set action(value: string) {
        this._action = value;
    }
    public get condition(): string {
        return this._condition
    }

    public set condition(value: string) {
        this._condition = value;
    }
    public get database(): string {
        return this._database
    }

    public set database(value: string) {
        this._database = value;
    }
    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    public get schema(): string {
        return this._schema
    }

    public set schema(value: string) {
        this._schema = value;
    }
    public get warehouse(): string {
        return this._warehouse
    }

    public set warehouse(value: string) {
        this._warehouse = value;
    }
    public get alert_schedule(): Alert_Alert_Schedule[] | undefined {
        return this._alert_schedule
    }

    public set alert_schedule(value: Alert_Alert_Schedule[] | undefined) {
        this._alert_schedule = value;
    }
    public get comment(): string | undefined {
        return this._comment
    }

    public set comment(value: string | undefined) {
        this._comment = value;
    }
    public get enabled(): boolean | undefined {
        return this._enabled
    }

    public set enabled(value: boolean | undefined) {
        this._enabled = value;
    }
}

