/*
DO NOT EDIT - Generated by main.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";

    export interface Dynamic_Table_Target_Lag {
        readonly downstream?: boolean;
        readonly maximum_duration?: string;
    }

export interface Dynamic_TableConfig extends TerraformMetaArguments {
    database: string;
    name: string;
    query: string;
    schema: string;
    target_lag: Dynamic_Table_Target_Lag[];
    warehouse: string;
    comment?: string;
    or_replace?: boolean;
}

export class Dynamic_Table extends TerraformResource {
    _database: string;
    _name: string;
    _query: string;
    _schema: string;
    _target_lag: Dynamic_Table_Target_Lag[];
    _warehouse: string;
    _comment?: string;
    _or_replace?: boolean;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Dynamic_TableConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_dynamic_table",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._database = config.database;
        
        this._name = config.name;
        
        this._query = config.query;
        
        this._schema = config.schema;
        
        this._target_lag = config.target_lag;
        
        this._warehouse = config.warehouse;
        
        this._comment = config.comment;
        
        this._or_replace = config.or_replace;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            database: this._database,
            name: this._name,
            query: this._query,
            schema: this._schema,
            target_lag: this._target_lag,
            warehouse: this._warehouse,
            comment: this._comment,
            or_replace: this._or_replace,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_dynamic_table.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get database(): string {
        return this._database
    }

    public set database(value: string) {
        this._database = value;
    }
    
    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    
    public get query(): string {
        return this._query
    }

    public set query(value: string) {
        this._query = value;
    }
    
    public get schema(): string {
        return this._schema
    }

    public set schema(value: string) {
        this._schema = value;
    }
    
    public get target_lag(): Dynamic_Table_Target_Lag[] {
        return this._target_lag
    }

    public set target_lag(value: Dynamic_Table_Target_Lag[]) {
        this._target_lag = value;
    }
    
    public get warehouse(): string {
        return this._warehouse
    }

    public set warehouse(value: string) {
        this._warehouse = value;
    }
    
    public get comment(): string | undefined {
        return this._comment
    }

    public set comment(value: string | undefined) {
        this._comment = value;
    }
    
    public get or_replace(): boolean | undefined {
        return this._or_replace
    }

    public set or_replace(value: boolean | undefined) {
        this._or_replace = value;
    }
    
}

