/*
DO NOT EDIT - Generated by main.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Email_Notification_IntegrationConfig extends TerraformMetaArguments {
    enabled: boolean;
    name: string;
    allowed_recipients?: Set<string>;
    comment?: string;
}

export class Email_Notification_Integration extends TerraformResource {
    _enabled: boolean;
    _name: string;
    _allowed_recipients?: Set<string>;
    _comment?: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Email_Notification_IntegrationConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_email_notification_integration",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._enabled = config.enabled;
        
        this._name = config.name;
        
        this._allowed_recipients = config.allowed_recipients;
        
        this._comment = config.comment;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            enabled: this._enabled,
            name: this._name,
            allowed_recipients: this._allowed_recipients,
            comment: this._comment,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_email_notification_integration.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get enabled(): boolean {
        return this._enabled
    }

    public set enabled(value: boolean) {
        this._enabled = value;
    }
    
    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    
    public get allowed_recipients(): Set<string> | undefined {
        return this._allowed_recipients
    }

    public set allowed_recipients(value: Set<string> | undefined) {
        this._allowed_recipients = value;
    }
    
    public get comment(): string | undefined {
        return this._comment
    }

    public set comment(value: string | undefined) {
        this._comment = value;
    }
    
}

