/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface External_Oauth_IntegrationConfig extends TerraformMetaArguments {
    enabled: boolean;
    issuer: string;
    name: string;
    snowflake_user_mapping_attribute: string;
    token_user_mapping_claims: Set<string>;
    type: string;
    allowed_roles?: Set<string>;
    any_role_mode?: string;
    audience_urls?: Set<string>;
    blocked_roles?: Set<string>;
    comment?: string;
    jws_keys_urls?: Set<string>;
    rsa_public_key?: string;
    rsa_public_key_2?: string;
    scope_delimiter?: string;
    scope_mapping_attribute?: string;
}

export class External_Oauth_Integration extends TerraformResource {
    _enabled: boolean;
    _issuer: string;
    _name: string;
    _snowflake_user_mapping_attribute: string;
    _token_user_mapping_claims: Set<string>;
    _type: string;
    _allowed_roles?: Set<string>;
    _any_role_mode?: string;
    _audience_urls?: Set<string>;
    _blocked_roles?: Set<string>;
    _comment?: string;
    _jws_keys_urls?: Set<string>;
    _rsa_public_key?: string;
    _rsa_public_key_2?: string;
    _scope_delimiter?: string;
    _scope_mapping_attribute?: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: External_Oauth_IntegrationConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_external_oauth_integration",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._enabled = config.enabled;
        
        this._issuer = config.issuer;
        
        this._name = config.name;
        
        this._snowflake_user_mapping_attribute = config.snowflake_user_mapping_attribute;
        
        this._token_user_mapping_claims = config.token_user_mapping_claims;
        
        this._type = config.type;
        
        this._allowed_roles = config.allowed_roles;
        
        this._any_role_mode = config.any_role_mode;
        
        this._audience_urls = config.audience_urls;
        
        this._blocked_roles = config.blocked_roles;
        
        this._comment = config.comment;
        
        this._jws_keys_urls = config.jws_keys_urls;
        
        this._rsa_public_key = config.rsa_public_key;
        
        this._rsa_public_key_2 = config.rsa_public_key_2;
        
        this._scope_delimiter = config.scope_delimiter;
        
        this._scope_mapping_attribute = config.scope_mapping_attribute;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            enabled: this._enabled,
            issuer: this._issuer,
            name: this._name,
            snowflake_user_mapping_attribute: this._snowflake_user_mapping_attribute,
            token_user_mapping_claims: this._token_user_mapping_claims,
            type: this._type,
            allowed_roles: this._allowed_roles,
            any_role_mode: this._any_role_mode,
            audience_urls: this._audience_urls,
            blocked_roles: this._blocked_roles,
            comment: this._comment,
            jws_keys_urls: this._jws_keys_urls,
            rsa_public_key: this._rsa_public_key,
            rsa_public_key_2: this._rsa_public_key_2,
            scope_delimiter: this._scope_delimiter,
            scope_mapping_attribute: this._scope_mapping_attribute,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_external_oauth_integration.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get enabled(): boolean {
        return this._enabled
    }

    public set enabled(value: boolean) {
        this._enabled = value;
    }
    
    public get issuer(): string {
        return this._issuer
    }

    public set issuer(value: string) {
        this._issuer = value;
    }
    
    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    
    public get snowflake_user_mapping_attribute(): string {
        return this._snowflake_user_mapping_attribute
    }

    public set snowflake_user_mapping_attribute(value: string) {
        this._snowflake_user_mapping_attribute = value;
    }
    
    public get token_user_mapping_claims(): Set<string> {
        return this._token_user_mapping_claims
    }

    public set token_user_mapping_claims(value: Set<string>) {
        this._token_user_mapping_claims = value;
    }
    
    public get type(): string {
        return this._type
    }

    public set type(value: string) {
        this._type = value;
    }
    
    public get allowed_roles(): Set<string> | undefined {
        return this._allowed_roles
    }

    public set allowed_roles(value: Set<string> | undefined) {
        this._allowed_roles = value;
    }
    
    public get any_role_mode(): string | undefined {
        return this._any_role_mode
    }

    public set any_role_mode(value: string | undefined) {
        this._any_role_mode = value;
    }
    
    public get audience_urls(): Set<string> | undefined {
        return this._audience_urls
    }

    public set audience_urls(value: Set<string> | undefined) {
        this._audience_urls = value;
    }
    
    public get blocked_roles(): Set<string> | undefined {
        return this._blocked_roles
    }

    public set blocked_roles(value: Set<string> | undefined) {
        this._blocked_roles = value;
    }
    
    public get comment(): string | undefined {
        return this._comment
    }

    public set comment(value: string | undefined) {
        this._comment = value;
    }
    
    public get jws_keys_urls(): Set<string> | undefined {
        return this._jws_keys_urls
    }

    public set jws_keys_urls(value: Set<string> | undefined) {
        this._jws_keys_urls = value;
    }
    
    public get rsa_public_key(): string | undefined {
        return this._rsa_public_key
    }

    public set rsa_public_key(value: string | undefined) {
        this._rsa_public_key = value;
    }
    
    public get rsa_public_key_2(): string | undefined {
        return this._rsa_public_key_2
    }

    public set rsa_public_key_2(value: string | undefined) {
        this._rsa_public_key_2 = value;
    }
    
    public get scope_delimiter(): string | undefined {
        return this._scope_delimiter
    }

    public set scope_delimiter(value: string | undefined) {
        this._scope_delimiter = value;
    }
    
    public get scope_mapping_attribute(): string | undefined {
        return this._scope_mapping_attribute
    }

    public set scope_mapping_attribute(value: string | undefined) {
        this._scope_mapping_attribute = value;
    }
    
}

