/*
DO NOT EDIT - Generated by main.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";

    export interface External_Function_Arg {
        readonly name: string;
        readonly type: string;
    }
    export interface External_Function_Header {
        readonly name: string;
        readonly value: string;
    }

export interface External_FunctionConfig extends TerraformMetaArguments {
    api_integration: string;
    database: string;
    name: string;
    return_behavior: string;
    return_type: string;
    schema: string;
    url_of_proxy_and_resource: string;
    arg?: External_Function_Arg[];
    comment?: string;
    compression?: string;
    context_headers?: string[];
    header?: External_Function_Header[];
    max_batch_rows?: number;
    null_input_behavior?: string;
    request_translator?: string;
    response_translator?: string;
    return_null_allowed?: boolean;
}

export class External_Function extends TerraformResource {
    _api_integration: string;
    _database: string;
    _name: string;
    _return_behavior: string;
    _return_type: string;
    _schema: string;
    _url_of_proxy_and_resource: string;
    _arg?: External_Function_Arg[];
    _comment?: string;
    _compression?: string;
    _context_headers?: string[];
    _header?: External_Function_Header[];
    _max_batch_rows?: number;
    _null_input_behavior?: string;
    _request_translator?: string;
    _response_translator?: string;
    _return_null_allowed?: boolean;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: External_FunctionConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_external_function",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._api_integration = config.api_integration;
        
        this._database = config.database;
        
        this._name = config.name;
        
        this._return_behavior = config.return_behavior;
        
        this._return_type = config.return_type;
        
        this._schema = config.schema;
        
        this._url_of_proxy_and_resource = config.url_of_proxy_and_resource;
        
        this._arg = config.arg;
        
        this._comment = config.comment;
        
        this._compression = config.compression;
        
        this._context_headers = config.context_headers;
        
        this._header = config.header;
        
        this._max_batch_rows = config.max_batch_rows;
        
        this._null_input_behavior = config.null_input_behavior;
        
        this._request_translator = config.request_translator;
        
        this._response_translator = config.response_translator;
        
        this._return_null_allowed = config.return_null_allowed;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            api_integration: this._api_integration,
            database: this._database,
            name: this._name,
            return_behavior: this._return_behavior,
            return_type: this._return_type,
            schema: this._schema,
            url_of_proxy_and_resource: this._url_of_proxy_and_resource,
            arg: this._arg,
            comment: this._comment,
            compression: this._compression,
            context_headers: this._context_headers,
            header: this._header,
            max_batch_rows: this._max_batch_rows,
            null_input_behavior: this._null_input_behavior,
            request_translator: this._request_translator,
            response_translator: this._response_translator,
            return_null_allowed: this._return_null_allowed,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_external_function.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get api_integration(): string {
        return this._api_integration
    }

    public set api_integration(value: string) {
        this._api_integration = value;
    }
    
    public get database(): string {
        return this._database
    }

    public set database(value: string) {
        this._database = value;
    }
    
    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    
    public get return_behavior(): string {
        return this._return_behavior
    }

    public set return_behavior(value: string) {
        this._return_behavior = value;
    }
    
    public get return_type(): string {
        return this._return_type
    }

    public set return_type(value: string) {
        this._return_type = value;
    }
    
    public get schema(): string {
        return this._schema
    }

    public set schema(value: string) {
        this._schema = value;
    }
    
    public get url_of_proxy_and_resource(): string {
        return this._url_of_proxy_and_resource
    }

    public set url_of_proxy_and_resource(value: string) {
        this._url_of_proxy_and_resource = value;
    }
    
    public get arg(): External_Function_Arg[] | undefined {
        return this._arg
    }

    public set arg(value: External_Function_Arg[] | undefined) {
        this._arg = value;
    }
    
    public get comment(): string | undefined {
        return this._comment
    }

    public set comment(value: string | undefined) {
        this._comment = value;
    }
    
    public get compression(): string | undefined {
        return this._compression
    }

    public set compression(value: string | undefined) {
        this._compression = value;
    }
    
    public get context_headers(): string[] | undefined {
        return this._context_headers
    }

    public set context_headers(value: string[] | undefined) {
        this._context_headers = value;
    }
    
    public get header(): External_Function_Header[] | undefined {
        return this._header
    }

    public set header(value: External_Function_Header[] | undefined) {
        this._header = value;
    }
    
    public get max_batch_rows(): number | undefined {
        return this._max_batch_rows
    }

    public set max_batch_rows(value: number | undefined) {
        this._max_batch_rows = value;
    }
    
    public get null_input_behavior(): string | undefined {
        return this._null_input_behavior
    }

    public set null_input_behavior(value: string | undefined) {
        this._null_input_behavior = value;
    }
    
    public get request_translator(): string | undefined {
        return this._request_translator
    }

    public set request_translator(value: string | undefined) {
        this._request_translator = value;
    }
    
    public get response_translator(): string | undefined {
        return this._response_translator
    }

    public set response_translator(value: string | undefined) {
        this._response_translator = value;
    }
    
    public get return_null_allowed(): boolean | undefined {
        return this._return_null_allowed
    }

    public set return_null_allowed(value: boolean | undefined) {
        this._return_null_allowed = value;
    }
    
}

