/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";

export interface  {
}

export interface Failover_GroupConfig extends TerraformMetaArguments {
    name: string;
    allowed_accounts?: string[];
    allowed_databases?: string[];
    allowed_integration_types?: string[];
    allowed_shares?: string[];
    from_replica?: Failover_Group_From_Replica[];
    ignore_edition_check?: boolean;
    object_types?: string[];
    replication_schedule?: Failover_Group_Replication_Schedule[];
}

export class Failover_Group extends TerraformResource {
    _name: string;
    _allowed_accounts?: string[];
    _allowed_databases?: string[];
    _allowed_integration_types?: string[];
    _allowed_shares?: string[];
    _from_replica?: Failover_Group_From_Replica[];
    _ignore_edition_check?: boolean;
    _object_types?: string[];
    _replication_schedule?: Failover_Group_Replication_Schedule[];
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Failover_GroupConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_failover_group",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._name = config.name;
        
        this._allowed_accounts = config.allowed_accounts;
        
        this._allowed_databases = config.allowed_databases;
        
        this._allowed_integration_types = config.allowed_integration_types;
        
        this._allowed_shares = config.allowed_shares;
        
        this._from_replica = config.from_replica;
        
        this._ignore_edition_check = config.ignore_edition_check;
        
        this._object_types = config.object_types;
        
        this._replication_schedule = config.replication_schedule;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            name: this._name,
            allowed_accounts: this._allowed_accounts,
            allowed_databases: this._allowed_databases,
            allowed_integration_types: this._allowed_integration_types,
            allowed_shares: this._allowed_shares,
            from_replica: this._from_replica,
            ignore_edition_check: this._ignore_edition_check,
            object_types: this._object_types,
            replication_schedule: this._replication_schedule,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_failover_group.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    public get allowed_accounts(): string[] | undefined {
        return this._allowed_accounts
    }

    public set allowed_accounts(value: string[] | undefined) {
        this._allowed_accounts = value;
    }
    public get allowed_databases(): string[] | undefined {
        return this._allowed_databases
    }

    public set allowed_databases(value: string[] | undefined) {
        this._allowed_databases = value;
    }
    public get allowed_integration_types(): string[] | undefined {
        return this._allowed_integration_types
    }

    public set allowed_integration_types(value: string[] | undefined) {
        this._allowed_integration_types = value;
    }
    public get allowed_shares(): string[] | undefined {
        return this._allowed_shares
    }

    public set allowed_shares(value: string[] | undefined) {
        this._allowed_shares = value;
    }
    public get from_replica(): Failover_Group_From_Replica[] | undefined {
        return this._from_replica
    }

    public set from_replica(value: Failover_Group_From_Replica[] | undefined) {
        this._from_replica = value;
    }
    public get ignore_edition_check(): boolean | undefined {
        return this._ignore_edition_check
    }

    public set ignore_edition_check(value: boolean | undefined) {
        this._ignore_edition_check = value;
    }
    public get object_types(): string[] | undefined {
        return this._object_types
    }

    public set object_types(value: string[] | undefined) {
        this._object_types = value;
    }
    public get replication_schedule(): Failover_Group_Replication_Schedule[] | undefined {
        return this._replication_schedule
    }

    public set replication_schedule(value: Failover_Group_Replication_Schedule[] | undefined) {
        this._replication_schedule = value;
    }
}

