/*
DO NOT EDIT - Generated by main.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Grant_Database_RoleConfig extends TerraformMetaArguments {
    database_role_name: string;
    parent_database_role_name?: string;
    parent_role_name?: string;
    share_name?: string;
}

export class Grant_Database_Role extends TerraformResource {
    _database_role_name: string;
    _parent_database_role_name?: string;
    _parent_role_name?: string;
    _share_name?: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Grant_Database_RoleConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_grant_database_role",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._database_role_name = config.database_role_name;
        
        this._parent_database_role_name = config.parent_database_role_name;
        
        this._parent_role_name = config.parent_role_name;
        
        this._share_name = config.share_name;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            database_role_name: this._database_role_name,
            parent_database_role_name: this._parent_database_role_name,
            parent_role_name: this._parent_role_name,
            share_name: this._share_name,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_grant_database_role.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get database_role_name(): string {
        return this._database_role_name
    }

    public set database_role_name(value: string) {
        this._database_role_name = value;
    }
    
    public get parent_database_role_name(): string | undefined {
        return this._parent_database_role_name
    }

    public set parent_database_role_name(value: string | undefined) {
        this._parent_database_role_name = value;
    }
    
    public get parent_role_name(): string | undefined {
        return this._parent_role_name
    }

    public set parent_role_name(value: string | undefined) {
        this._parent_role_name = value;
    }
    
    public get share_name(): string | undefined {
        return this._share_name
    }

    public set share_name(value: string | undefined) {
        this._share_name = value;
    }
    
}

