/*
DO NOT EDIT - Generated by main.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Grant_Account_RoleConfig extends TerraformMetaArguments {
    role_name: string;
    parent_role_name?: string;
    user_name?: string;
}

export class Grant_Account_Role extends TerraformResource {
    _role_name: string;
    _parent_role_name?: string;
    _user_name?: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Grant_Account_RoleConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_grant_account_role",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._role_name = config.role_name;
        
        this._parent_role_name = config.parent_role_name;
        
        this._user_name = config.user_name;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            role_name: this._role_name,
            parent_role_name: this._parent_role_name,
            user_name: this._user_name,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_grant_account_role.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get role_name(): string {
        return this._role_name
    }

    public set role_name(value: string) {
        this._role_name = value;
    }
    
    public get parent_role_name(): string | undefined {
        return this._parent_role_name
    }

    public set parent_role_name(value: string | undefined) {
        this._parent_role_name = value;
    }
    
    public get user_name(): string | undefined {
        return this._user_name
    }

    public set user_name(value: string | undefined) {
        this._user_name = value;
    }
    
}

