/*
DO NOT EDIT - Generated by main.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Managed_AccountConfig extends TerraformMetaArguments {
    admin_name: string;
    admin_password: string;
    name: string;
    comment?: string;
    type?: string;
}

export class Managed_Account extends TerraformResource {
    _admin_name: string;
    _admin_password: string;
    _name: string;
    _comment?: string;
    _type?: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Managed_AccountConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_managed_account",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._admin_name = config.admin_name;
        
        this._admin_password = config.admin_password;
        
        this._name = config.name;
        
        this._comment = config.comment;
        
        this._type = config.type;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            admin_name: this._admin_name,
            admin_password: this._admin_password,
            name: this._name,
            comment: this._comment,
            type: this._type,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_managed_account.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get admin_name(): string {
        return this._admin_name
    }

    public set admin_name(value: string) {
        this._admin_name = value;
    }
    
    public get admin_password(): string {
        return this._admin_password
    }

    public set admin_password(value: string) {
        this._admin_password = value;
    }
    
    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    
    public get comment(): string | undefined {
        return this._comment
    }

    public set comment(value: string | undefined) {
        this._comment = value;
    }
    
    public get type(): string | undefined {
        return this._type
    }

    public set type(value: string | undefined) {
        this._type = value;
    }
    
}

