/*
DO NOT EDIT - Generated by main.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Network_Policy_AttachmentConfig extends TerraformMetaArguments {
    network_policy_name: string;
    set_for_account?: boolean;
    users?: Set<string>;
}

export class Network_Policy_Attachment extends TerraformResource {
    _network_policy_name: string;
    _set_for_account?: boolean;
    _users?: Set<string>;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Network_Policy_AttachmentConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_network_policy_attachment",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._network_policy_name = config.network_policy_name;
        
        this._set_for_account = config.set_for_account;
        
        this._users = config.users;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            network_policy_name: this._network_policy_name,
            set_for_account: this._set_for_account,
            users: this._users,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_network_policy_attachment.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get network_policy_name(): string {
        return this._network_policy_name
    }

    public set network_policy_name(value: string) {
        this._network_policy_name = value;
    }
    
    public get set_for_account(): boolean | undefined {
        return this._set_for_account
    }

    public set set_for_account(value: boolean | undefined) {
        this._set_for_account = value;
    }
    
    public get users(): Set<string> | undefined {
        return this._users
    }

    public set users(value: Set<string> | undefined) {
        this._users = value;
    }
    
}

