/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Network_PolicyConfig extends TerraformMetaArguments {
    allowed_ip_list: Set<string>;
    name: string;
    blocked_ip_list?: Set<string>;
    comment?: string;
}

export class Network_Policy extends TerraformResource {
    _allowed_ip_list: Set<string>;
    _name: string;
    _blocked_ip_list?: Set<string>;
    _comment?: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Network_PolicyConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_network_policy",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._allowed_ip_list = config.allowed_ip_list;
        
        this._name = config.name;
        
        this._blocked_ip_list = config.blocked_ip_list;
        
        this._comment = config.comment;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            allowed_ip_list: this._allowed_ip_list,
            name: this._name,
            blocked_ip_list: this._blocked_ip_list,
            comment: this._comment,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_network_policy.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get allowed_ip_list(): Set<string> {
        return this._allowed_ip_list
    }

    public set allowed_ip_list(value: Set<string>) {
        this._allowed_ip_list = value;
    }
    
    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    
    public get blocked_ip_list(): Set<string> | undefined {
        return this._blocked_ip_list
    }

    public set blocked_ip_list(value: Set<string> | undefined) {
        this._blocked_ip_list = value;
    }
    
    public get comment(): string | undefined {
        return this._comment
    }

    public set comment(value: string | undefined) {
        this._comment = value;
    }
    
}

