/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Notification_IntegrationConfig extends TerraformMetaArguments {
    name: string;
    aws_sns_role_arn?: string;
    aws_sns_topic_arn?: string;
    aws_sqs_arn?: string;
    aws_sqs_role_arn?: string;
    azure_storage_queue_primary_uri?: string;
    azure_tenant_id?: string;
    comment?: string;
    direction?: string;
    enabled?: boolean;
    gcp_pubsub_subscription_name?: string;
    gcp_pubsub_topic_name?: string;
    notification_provider?: string;
    type?: string;
}

export class Notification_Integration extends TerraformResource {
    _name: string;
    _aws_sns_role_arn?: string;
    _aws_sns_topic_arn?: string;
    _aws_sqs_arn?: string;
    _aws_sqs_role_arn?: string;
    _azure_storage_queue_primary_uri?: string;
    _azure_tenant_id?: string;
    _comment?: string;
    _direction?: string;
    _enabled?: boolean;
    _gcp_pubsub_subscription_name?: string;
    _gcp_pubsub_topic_name?: string;
    _notification_provider?: string;
    _type?: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Notification_IntegrationConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_notification_integration",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._name = config.name;
        
        this._aws_sns_role_arn = config.aws_sns_role_arn;
        
        this._aws_sns_topic_arn = config.aws_sns_topic_arn;
        
        this._aws_sqs_arn = config.aws_sqs_arn;
        
        this._aws_sqs_role_arn = config.aws_sqs_role_arn;
        
        this._azure_storage_queue_primary_uri = config.azure_storage_queue_primary_uri;
        
        this._azure_tenant_id = config.azure_tenant_id;
        
        this._comment = config.comment;
        
        this._direction = config.direction;
        
        this._enabled = config.enabled;
        
        this._gcp_pubsub_subscription_name = config.gcp_pubsub_subscription_name;
        
        this._gcp_pubsub_topic_name = config.gcp_pubsub_topic_name;
        
        this._notification_provider = config.notification_provider;
        
        this._type = config.type;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            name: this._name,
            aws_sns_role_arn: this._aws_sns_role_arn,
            aws_sns_topic_arn: this._aws_sns_topic_arn,
            aws_sqs_arn: this._aws_sqs_arn,
            aws_sqs_role_arn: this._aws_sqs_role_arn,
            azure_storage_queue_primary_uri: this._azure_storage_queue_primary_uri,
            azure_tenant_id: this._azure_tenant_id,
            comment: this._comment,
            direction: this._direction,
            enabled: this._enabled,
            gcp_pubsub_subscription_name: this._gcp_pubsub_subscription_name,
            gcp_pubsub_topic_name: this._gcp_pubsub_topic_name,
            notification_provider: this._notification_provider,
            type: this._type,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_notification_integration.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    public get aws_sns_role_arn(): string | undefined {
        return this._aws_sns_role_arn
    }

    public set aws_sns_role_arn(value: string | undefined) {
        this._aws_sns_role_arn = value;
    }
    public get aws_sns_topic_arn(): string | undefined {
        return this._aws_sns_topic_arn
    }

    public set aws_sns_topic_arn(value: string | undefined) {
        this._aws_sns_topic_arn = value;
    }
    public get aws_sqs_arn(): string | undefined {
        return this._aws_sqs_arn
    }

    public set aws_sqs_arn(value: string | undefined) {
        this._aws_sqs_arn = value;
    }
    public get aws_sqs_role_arn(): string | undefined {
        return this._aws_sqs_role_arn
    }

    public set aws_sqs_role_arn(value: string | undefined) {
        this._aws_sqs_role_arn = value;
    }
    public get azure_storage_queue_primary_uri(): string | undefined {
        return this._azure_storage_queue_primary_uri
    }

    public set azure_storage_queue_primary_uri(value: string | undefined) {
        this._azure_storage_queue_primary_uri = value;
    }
    public get azure_tenant_id(): string | undefined {
        return this._azure_tenant_id
    }

    public set azure_tenant_id(value: string | undefined) {
        this._azure_tenant_id = value;
    }
    public get comment(): string | undefined {
        return this._comment
    }

    public set comment(value: string | undefined) {
        this._comment = value;
    }
    public get direction(): string | undefined {
        return this._direction
    }

    public set direction(value: string | undefined) {
        this._direction = value;
    }
    public get enabled(): boolean | undefined {
        return this._enabled
    }

    public set enabled(value: boolean | undefined) {
        this._enabled = value;
    }
    public get gcp_pubsub_subscription_name(): string | undefined {
        return this._gcp_pubsub_subscription_name
    }

    public set gcp_pubsub_subscription_name(value: string | undefined) {
        this._gcp_pubsub_subscription_name = value;
    }
    public get gcp_pubsub_topic_name(): string | undefined {
        return this._gcp_pubsub_topic_name
    }

    public set gcp_pubsub_topic_name(value: string | undefined) {
        this._gcp_pubsub_topic_name = value;
    }
    public get notification_provider(): string | undefined {
        return this._notification_provider
    }

    public set notification_provider(value: string | undefined) {
        this._notification_provider = value;
    }
    public get type(): string | undefined {
        return this._type
    }

    public set type(value: string | undefined) {
        this._type = value;
    }
}

