/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Resource_MonitorConfig extends TerraformMetaArguments {
    name: string;
    credit_quota?: number;
    end_timestamp?: string;
    frequency?: string;
    notify_triggers?: Set<number>;
    notify_users?: Set<string>;
    set_for_account?: boolean;
    start_timestamp?: string;
    suspend_immediate_trigger?: number;
    suspend_immediate_triggers?: Set<number>;
    suspend_trigger?: number;
    suspend_triggers?: Set<number>;
    warehouses?: Set<string>;
}

export class Resource_Monitor extends TerraformResource {
    _name: string;
    _credit_quota?: number;
    _end_timestamp?: string;
    _frequency?: string;
    _notify_triggers?: Set<number>;
    _notify_users?: Set<string>;
    _set_for_account?: boolean;
    _start_timestamp?: string;
    _suspend_immediate_trigger?: number;
    _suspend_immediate_triggers?: Set<number>;
    _suspend_trigger?: number;
    _suspend_triggers?: Set<number>;
    _warehouses?: Set<string>;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Resource_MonitorConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_resource_monitor",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._name = config.name;
        
        this._credit_quota = config.credit_quota;
        
        this._end_timestamp = config.end_timestamp;
        
        this._frequency = config.frequency;
        
        this._notify_triggers = config.notify_triggers;
        
        this._notify_users = config.notify_users;
        
        this._set_for_account = config.set_for_account;
        
        this._start_timestamp = config.start_timestamp;
        
        this._suspend_immediate_trigger = config.suspend_immediate_trigger;
        
        this._suspend_immediate_triggers = config.suspend_immediate_triggers;
        
        this._suspend_trigger = config.suspend_trigger;
        
        this._suspend_triggers = config.suspend_triggers;
        
        this._warehouses = config.warehouses;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            name: this._name,
            credit_quota: this._credit_quota,
            end_timestamp: this._end_timestamp,
            frequency: this._frequency,
            notify_triggers: this._notify_triggers,
            notify_users: this._notify_users,
            set_for_account: this._set_for_account,
            start_timestamp: this._start_timestamp,
            suspend_immediate_trigger: this._suspend_immediate_trigger,
            suspend_immediate_triggers: this._suspend_immediate_triggers,
            suspend_trigger: this._suspend_trigger,
            suspend_triggers: this._suspend_triggers,
            warehouses: this._warehouses,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_resource_monitor.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    
    public get credit_quota(): number | undefined {
        return this._credit_quota
    }

    public set credit_quota(value: number | undefined) {
        this._credit_quota = value;
    }
    
    public get end_timestamp(): string | undefined {
        return this._end_timestamp
    }

    public set end_timestamp(value: string | undefined) {
        this._end_timestamp = value;
    }
    
    public get frequency(): string | undefined {
        return this._frequency
    }

    public set frequency(value: string | undefined) {
        this._frequency = value;
    }
    
    public get notify_triggers(): Set<number> | undefined {
        return this._notify_triggers
    }

    public set notify_triggers(value: Set<number> | undefined) {
        this._notify_triggers = value;
    }
    
    public get notify_users(): Set<string> | undefined {
        return this._notify_users
    }

    public set notify_users(value: Set<string> | undefined) {
        this._notify_users = value;
    }
    
    public get set_for_account(): boolean | undefined {
        return this._set_for_account
    }

    public set set_for_account(value: boolean | undefined) {
        this._set_for_account = value;
    }
    
    public get start_timestamp(): string | undefined {
        return this._start_timestamp
    }

    public set start_timestamp(value: string | undefined) {
        this._start_timestamp = value;
    }
    
    public get suspend_immediate_trigger(): number | undefined {
        return this._suspend_immediate_trigger
    }

    public set suspend_immediate_trigger(value: number | undefined) {
        this._suspend_immediate_trigger = value;
    }
    
    public get suspend_immediate_triggers(): Set<number> | undefined {
        return this._suspend_immediate_triggers
    }

    public set suspend_immediate_triggers(value: Set<number> | undefined) {
        this._suspend_immediate_triggers = value;
    }
    
    public get suspend_trigger(): number | undefined {
        return this._suspend_trigger
    }

    public set suspend_trigger(value: number | undefined) {
        this._suspend_trigger = value;
    }
    
    public get suspend_triggers(): Set<number> | undefined {
        return this._suspend_triggers
    }

    public set suspend_triggers(value: Set<number> | undefined) {
        this._suspend_triggers = value;
    }
    
    public get warehouses(): Set<string> | undefined {
        return this._warehouses
    }

    public set warehouses(value: Set<string> | undefined) {
        this._warehouses = value;
    }
    
}

