/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Role_GrantsConfig extends TerraformMetaArguments {
    role_name: string;
    enable_multiple_grants?: boolean;
    roles?: Set<string>;
    users?: Set<string>;
}

export class Role_Grants extends TerraformResource {
    _role_name: string;
    _enable_multiple_grants?: boolean;
    _roles?: Set<string>;
    _users?: Set<string>;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Role_GrantsConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_role_grants",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._role_name = config.role_name;
        
        this._enable_multiple_grants = config.enable_multiple_grants;
        
        this._roles = config.roles;
        
        this._users = config.users;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            role_name: this._role_name,
            enable_multiple_grants: this._enable_multiple_grants,
            roles: this._roles,
            users: this._users,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_role_grants.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get role_name(): string {
        return this._role_name
    }

    public set role_name(value: string) {
        this._role_name = value;
    }
    
    public get enable_multiple_grants(): boolean | undefined {
        return this._enable_multiple_grants
    }

    public set enable_multiple_grants(value: boolean | undefined) {
        this._enable_multiple_grants = value;
    }
    
    public get roles(): Set<string> | undefined {
        return this._roles
    }

    public set roles(value: Set<string> | undefined) {
        this._roles = value;
    }
    
    public get users(): Set<string> | undefined {
        return this._users
    }

    public set users(value: Set<string> | undefined) {
        this._users = value;
    }
    
}

