/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Role_Ownership_GrantConfig extends TerraformMetaArguments {
    on_role_name: string;
    to_role_name: string;
    current_grants?: string;
    revert_ownership_to_role_name?: string;
}

export class Role_Ownership_Grant extends TerraformResource {
    _on_role_name: string;
    _to_role_name: string;
    _current_grants?: string;
    _revert_ownership_to_role_name?: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Role_Ownership_GrantConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_role_ownership_grant",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._on_role_name = config.on_role_name;
        
        this._to_role_name = config.to_role_name;
        
        this._current_grants = config.current_grants;
        
        this._revert_ownership_to_role_name = config.revert_ownership_to_role_name;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            on_role_name: this._on_role_name,
            to_role_name: this._to_role_name,
            current_grants: this._current_grants,
            revert_ownership_to_role_name: this._revert_ownership_to_role_name,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_role_ownership_grant.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get on_role_name(): string {
        return this._on_role_name
    }

    public set on_role_name(value: string) {
        this._on_role_name = value;
    }
    public get to_role_name(): string {
        return this._to_role_name
    }

    public set to_role_name(value: string) {
        this._to_role_name = value;
    }
    public get current_grants(): string | undefined {
        return this._current_grants
    }

    public set current_grants(value: string | undefined) {
        this._current_grants = value;
    }
    public get revert_ownership_to_role_name(): string | undefined {
        return this._revert_ownership_to_role_name
    }

    public set revert_ownership_to_role_name(value: string | undefined) {
        this._revert_ownership_to_role_name = value;
    }
}

