/*
DO NOT EDIT - Generated by main.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Row_Access_PolicyConfig extends TerraformMetaArguments {
    database: string;
    name: string;
    row_access_expression: string;
    schema: string;
    signature: Record<string, string>;
    comment?: string;
}

export class Row_Access_Policy extends TerraformResource {
    _database: string;
    _name: string;
    _row_access_expression: string;
    _schema: string;
    _signature: Record<string, string>;
    _comment?: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Row_Access_PolicyConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_row_access_policy",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._database = config.database;
        
        this._name = config.name;
        
        this._row_access_expression = config.row_access_expression;
        
        this._schema = config.schema;
        
        this._signature = config.signature;
        
        this._comment = config.comment;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            database: this._database,
            name: this._name,
            row_access_expression: this._row_access_expression,
            schema: this._schema,
            signature: this._signature,
            comment: this._comment,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_row_access_policy.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get database(): string {
        return this._database
    }

    public set database(value: string) {
        this._database = value;
    }
    
    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    
    public get row_access_expression(): string {
        return this._row_access_expression
    }

    public set row_access_expression(value: string) {
        this._row_access_expression = value;
    }
    
    public get schema(): string {
        return this._schema
    }

    public set schema(value: string) {
        this._schema = value;
    }
    
    public get signature(): Record<string, string> {
        return this._signature
    }

    public set signature(value: Record<string, string>) {
        this._signature = value;
    }
    
    public get comment(): string | undefined {
        return this._comment
    }

    public set comment(value: string | undefined) {
        this._comment = value;
    }
    
}

