/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Scim_IntegrationConfig extends TerraformMetaArguments {
    name: string;
    provisioner_role: string;
    scim_client: string;
    network_policy?: string;
}

export class Scim_Integration extends TerraformResource {
    _name: string;
    _provisioner_role: string;
    _scim_client: string;
    _network_policy?: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Scim_IntegrationConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_scim_integration",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._name = config.name;
        
        this._provisioner_role = config.provisioner_role;
        
        this._scim_client = config.scim_client;
        
        this._network_policy = config.network_policy;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            name: this._name,
            provisioner_role: this._provisioner_role,
            scim_client: this._scim_client,
            network_policy: this._network_policy,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_scim_integration.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    
    public get provisioner_role(): string {
        return this._provisioner_role
    }

    public set provisioner_role(value: string) {
        this._provisioner_role = value;
    }
    
    public get scim_client(): string {
        return this._scim_client
    }

    public set scim_client(value: string) {
        this._scim_client = value;
    }
    
    public get network_policy(): string | undefined {
        return this._network_policy
    }

    public set network_policy(value: string | undefined) {
        this._network_policy = value;
    }
    
}

