/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Session_ParameterConfig extends TerraformMetaArguments {
    key: string;
    value: string;
    on_account?: boolean;
    user?: string;
}

export class Session_Parameter extends TerraformResource {
    _key: string;
    _value: string;
    _on_account?: boolean;
    _user?: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Session_ParameterConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_session_parameter",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._key = config.key;
        
        this._value = config.value;
        
        this._on_account = config.on_account;
        
        this._user = config.user;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            key: this._key,
            value: this._value,
            on_account: this._on_account,
            user: this._user,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_session_parameter.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get key(): string {
        return this._key
    }

    public set key(value: string) {
        this._key = value;
    }
    
    public get value(): string {
        return this._value
    }

    public set value(value: string) {
        this._value = value;
    }
    
    public get on_account(): boolean | undefined {
        return this._on_account
    }

    public set on_account(value: boolean | undefined) {
        this._on_account = value;
    }
    
    public get user(): string | undefined {
        return this._user
    }

    public set user(value: string | undefined) {
        this._user = value;
    }
    
}

