/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface ShareConfig extends TerraformMetaArguments {
    name: string;
    accounts?: string[];
    comment?: string;
}

export class Share extends TerraformResource {
    _name: string;
    _accounts?: string[];
    _comment?: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: ShareConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_share",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._name = config.name;
        
        this._accounts = config.accounts;
        
        this._comment = config.comment;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            name: this._name,
            accounts: this._accounts,
            comment: this._comment,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_share.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    
    public get accounts(): string[] | undefined {
        return this._accounts
    }

    public set accounts(value: string[] | undefined) {
        this._accounts = value;
    }
    
    public get comment(): string | undefined {
        return this._comment
    }

    public set comment(value: string | undefined) {
        this._comment = value;
    }
    
}

