/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";

export interface  {
}

export interface StageConfig extends TerraformMetaArguments {
    database: string;
    name: string;
    schema: string;
    aws_external_id?: string;
    comment?: string;
    copy_options?: string;
    credentials?: string;
    directory?: string;
    encryption?: string;
    file_format?: string;
    snowflake_iam_user?: string;
    storage_integration?: string;
    tag?: Stage_Tag[];
    url?: string;
}

export class Stage extends TerraformResource {
    _database: string;
    _name: string;
    _schema: string;
    _aws_external_id?: string;
    _comment?: string;
    _copy_options?: string;
    _credentials?: string;
    _directory?: string;
    _encryption?: string;
    _file_format?: string;
    _snowflake_iam_user?: string;
    _storage_integration?: string;
    _tag?: Stage_Tag[];
    _url?: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: StageConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_stage",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._database = config.database;
        
        this._name = config.name;
        
        this._schema = config.schema;
        
        this._aws_external_id = config.aws_external_id;
        
        this._comment = config.comment;
        
        this._copy_options = config.copy_options;
        
        this._credentials = config.credentials;
        
        this._directory = config.directory;
        
        this._encryption = config.encryption;
        
        this._file_format = config.file_format;
        
        this._snowflake_iam_user = config.snowflake_iam_user;
        
        this._storage_integration = config.storage_integration;
        
        this._tag = config.tag;
        
        this._url = config.url;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            database: this._database,
            name: this._name,
            schema: this._schema,
            aws_external_id: this._aws_external_id,
            comment: this._comment,
            copy_options: this._copy_options,
            credentials: this._credentials,
            directory: this._directory,
            encryption: this._encryption,
            file_format: this._file_format,
            snowflake_iam_user: this._snowflake_iam_user,
            storage_integration: this._storage_integration,
            tag: this._tag,
            url: this._url,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_stage.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get database(): string {
        return this._database
    }

    public set database(value: string) {
        this._database = value;
    }
    public get name(): string {
        return this._name
    }

    public set name(value: string) {
        this._name = value;
    }
    public get schema(): string {
        return this._schema
    }

    public set schema(value: string) {
        this._schema = value;
    }
    public get aws_external_id(): string | undefined {
        return this._aws_external_id
    }

    public set aws_external_id(value: string | undefined) {
        this._aws_external_id = value;
    }
    public get comment(): string | undefined {
        return this._comment
    }

    public set comment(value: string | undefined) {
        this._comment = value;
    }
    public get copy_options(): string | undefined {
        return this._copy_options
    }

    public set copy_options(value: string | undefined) {
        this._copy_options = value;
    }
    public get credentials(): string | undefined {
        return this._credentials
    }

    public set credentials(value: string | undefined) {
        this._credentials = value;
    }
    public get directory(): string | undefined {
        return this._directory
    }

    public set directory(value: string | undefined) {
        this._directory = value;
    }
    public get encryption(): string | undefined {
        return this._encryption
    }

    public set encryption(value: string | undefined) {
        this._encryption = value;
    }
    public get file_format(): string | undefined {
        return this._file_format
    }

    public set file_format(value: string | undefined) {
        this._file_format = value;
    }
    public get snowflake_iam_user(): string | undefined {
        return this._snowflake_iam_user
    }

    public set snowflake_iam_user(value: string | undefined) {
        this._snowflake_iam_user = value;
    }
    public get storage_integration(): string | undefined {
        return this._storage_integration
    }

    public set storage_integration(value: string | undefined) {
        this._storage_integration = value;
    }
    public get tag(): Stage_Tag[] | undefined {
        return this._tag
    }

    public set tag(value: Stage_Tag[] | undefined) {
        this._tag = value;
    }
    public get url(): string | undefined {
        return this._url
    }

    public set url(value: string | undefined) {
        this._url = value;
    }
}

