/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface Table_Column_Masking_Policy_ApplicationConfig extends TerraformMetaArguments {
    column: string;
    masking_policy: string;
    table: string;
}

export class Table_Column_Masking_Policy_Application extends TerraformResource {
    _column: string;
    _masking_policy: string;
    _table: string;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: Table_Column_Masking_Policy_ApplicationConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_table_column_masking_policy_application",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._column = config.column;
        
        this._masking_policy = config.masking_policy;
        
        this._table = config.table;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            column: this._column,
            masking_policy: this._masking_policy,
            table: this._table,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_table_column_masking_policy_application.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get column(): string {
        return this._column
    }

    public set column(value: string) {
        this._column = value;
    }
    
    public get masking_policy(): string {
        return this._masking_policy
    }

    public set masking_policy(value: string) {
        this._masking_policy = value;
    }
    
    public get table(): string {
        return this._table
    }

    public set table(value: string) {
        this._table = value;
    }
    
}

