/*
DO NOT EDIT - Generated by tools/create_cdk_provider_files.js. Refer to the README for more info.
*/

import { TerraformMetaArguments, TerraformResource } from "cdktf";
import { Construct } from "constructs";


export interface User_GrantConfig extends TerraformMetaArguments {
    privilege: string;
    user_name: string;
    enable_multiple_grants?: boolean;
    roles?: Set<string>;
    with_grant_option?: boolean;
}

export class User_Grant extends TerraformResource {
    _privilege: string;
    _user_name: string;
    _enable_multiple_grants?: boolean;
    _roles?: Set<string>;
    _with_grant_option?: boolean;
    readonly _id: string;

    public constructor(scope: Construct, id: string, config: User_GrantConfig) {
        super(scope, id, {
            terraformResourceType: "snowflake_user_grant",
            terraformGeneratorMetadata: {
                providerName: "snowflake"
            },
            provider: config.provider,
            dependsOn: config.dependsOn,
            count: config.count,
            lifecycle: config.lifecycle
        });
        this._id = id;
        
        this._privilege = config.privilege;
        
        this._user_name = config.user_name;
        
        this._enable_multiple_grants = config.enable_multiple_grants;
        
        this._roles = config.roles;
        
        this._with_grant_option = config.with_grant_option;
    }
    public getAttributes(): { [name: string]: any } {
        return {
            privilege: this._privilege,
            user_name: this._user_name,
            enable_multiple_grants: this._enable_multiple_grants,
            roles: this._roles,
            with_grant_option: this._with_grant_option,
        }
    }

    public get id(): string {
        return this._id;
    }

    public ref(attribute: string): string {
        return `\${snowflake_user_grant.${this.friendlyUniqueId}.${attribute}}`;
    }

    public get privilege(): string {
        return this._privilege
    }

    public set privilege(value: string) {
        this._privilege = value;
    }
    
    public get user_name(): string {
        return this._user_name
    }

    public set user_name(value: string) {
        this._user_name = value;
    }
    
    public get enable_multiple_grants(): boolean | undefined {
        return this._enable_multiple_grants
    }

    public set enable_multiple_grants(value: boolean | undefined) {
        this._enable_multiple_grants = value;
    }
    
    public get roles(): Set<string> | undefined {
        return this._roles
    }

    public set roles(value: Set<string> | undefined) {
        this._roles = value;
    }
    
    public get with_grant_option(): boolean | undefined {
        return this._with_grant_option
    }

    public set with_grant_option(value: boolean | undefined) {
        this._with_grant_option = value;
    }
    
}

